name: "kyverno"
version: "v1.10.0"
usage: "runs kyverno cli against templated helm resources"
description: "runs kyverno cli against templated helm resources"
command: "$HELM_PLUGIN_DIR/scripts/run.sh"
hooks:
  install: "cd $HELM_PLUGIN_DIR; scripts/install_plugin.sh"
  update: "cd $HELM_PLUGIN_DIR; scripts/install_plugin.sh"
